using System.Drawing.Imaging;
using System.Text;

namespace WxBridge.Windows;

internal sealed class MarkdownCaptureWriter
{
    private readonly object _sync = new();
    private readonly string _outputPath;
    private readonly string _outputDir;
    private readonly string _assetsDir;
    private int _imageIndex;
    private string? _speaker;

    public MarkdownCaptureWriter(string outputPath)
    {
        _outputPath = Path.GetFullPath(outputPath);
        _outputDir = Path.GetDirectoryName(_outputPath) ?? Environment.CurrentDirectory;
        _assetsDir = Path.Combine(_outputDir, Path.GetFileNameWithoutExtension(_outputPath) + "_assets");
        Directory.CreateDirectory(_outputDir);
        Directory.CreateDirectory(_assetsDir);
        _imageIndex = GetLastImageIndex(_assetsDir);

        if (!File.Exists(_outputPath))
        {
            File.WriteAllText(_outputPath, "<!-- Generated by WxBridge capture mode. -->\n\n", Encoding.UTF8);
        }
    }

    public void SetSpeaker(string speaker)
    {
        lock (_sync)
        {
            _speaker = speaker;
            File.AppendAllText(_outputPath, $"# {speaker}\n\n", Encoding.UTF8);
        }
    }

    public void AppendText(string text)
    {
        lock (_sync)
        {
            EnsureSpeaker();
            File.AppendAllText(_outputPath, text.Trim() + "\n\n", Encoding.UTF8);
        }
    }

    public void AppendImage(System.Drawing.Image image)
    {
        lock (_sync)
        {
            EnsureSpeaker();
            _imageIndex++;
            var imagePath = Path.Combine(_assetsDir, $"image-{_imageIndex:000}.png");
            image.Save(imagePath, ImageFormat.Png);
            var relativePath = Path.GetRelativePath(_outputDir, imagePath).Replace('\\', '/');
            File.AppendAllText(_outputPath, $"![]({relativePath})\n\n", Encoding.UTF8);
        }
    }

    private static int GetLastImageIndex(string assetsDir)
    {
        var max = 0;
        foreach (var path in Directory.EnumerateFiles(assetsDir, "image-*.png"))
        {
            var name = Path.GetFileNameWithoutExtension(path);
            if (name.Length == 9
                && int.TryParse(name.AsSpan(6, 3), out var index)
                && index > max)
            {
                max = index;
            }
        }

        return max;
    }

    private void EnsureSpeaker()
    {
        if (!string.IsNullOrWhiteSpace(_speaker))
        {
            return;
        }

        _speaker = "未指定";
        File.AppendAllText(_outputPath, "# 未指定\n\n", Encoding.UTF8);
    }
}
